### PR TITLE
Fix cljs camel-case

### LINKED ISSUE #11: camel-case broken for CLJS
**Environment**
lein-cljsbuild Rhino REPL

**To reproduce**
1. Run `lein trampoline cljsbuild repl-rhino`
2. Enter `(require 'inflections.core)`
3. Enter `(inflections.core/camel-case "this-that")`

The result is "This-T-hat", rather than the expected "ThisThat". Is this known/intended behaviour?

### PR DESCRIPTION
**Pull request by okal**
Closes #11

### CODE REVIEW

**Comment by r0man** [comment]
@okal Could you also please add a test case for this? Thanks!

**Comment by okal** [comment]
@r0man  The API is unchanged, so the previous test cases cover the full functionality. The tests break when you upgrade to _ClojureScript 1.7.145_, and the behaviour is as described in #11. I now believe what caused it was that the code calling `inflections.core/camel-case` was on _1.7.145_, but `inflections` was still on an older version. Perhaps that calls for a different kind of fix?

**Comment by okal** [comment]
Perhaps this change will cause problems for users on older versions of ClojureScript?

**Comment by r0man** [comment]
@okal Ok, I see. I'll merge it

**Comment by r0man** [comment]
Released as `0.10.0`.

**Comment by okal** [comment]
Thank you :-)

**Pull request merged**
